import { db } from './db';
import { medications } from '../shared/schema';
import { eq } from 'drizzle-orm';

/**
 * Comprehensive medication database seed
 * Includes common medications across all categories
 */
export async function seedMedications() {
  try {
    console.log('🌱 Seeding medications database...');

    // Check if medications already exist
    const existing = await db.select().from(medications).limit(1);
    if (existing.length > 0) {
      console.log('⏭️  Medications already seeded, skipping...');
      // Get actual count
      const all = await db.select().from(medications);
      return { message: 'Medications already exist', count: all.length, medications: all.map(m => m.name) };
    }

    const commonMedications = [
      // ANALGESICS & ANTIPYRETICS
      {
        name: 'Paracetamol',
        genericName: 'Acetaminophen',
        brandName: 'Panadol, Tylenol',
        category: 'Analgesic',
        dosageForm: 'Tablet',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Paracetamol',
        indications: 'Pain relief, fever reduction, headache, toothache, muscle aches',
        contraindications: 'Severe liver disease, hypersensitivity to paracetamol',
        sideEffects: 'Rare: allergic reactions, liver damage (overdose)',
        dosageAdult: '500-1000mg',
        dosageChild: '10-15mg/kg',
        frequency: 'Every 4-6 hours (max 4g/day)',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '5.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Ibuprofen',
        genericName: 'Ibuprofen',
        brandName: 'Advil, Motrin, Brufen',
        category: 'NSAID',
        dosageForm: 'Tablet',
        strength: '400mg',
        manufacturer: 'Various',
        activeIngredient: 'Ibuprofen',
        indications: 'Pain, inflammation, fever, arthritis, menstrual cramps',
        contraindications: 'Active peptic ulcer, severe heart failure, third trimester pregnancy',
        sideEffects: 'Stomach upset, nausea, heartburn, dizziness, rash',
        dosageAdult: '400-600mg',
        dosageChild: '5-10mg/kg',
        frequency: 'Every 6-8 hours with food',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '8.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Diclofenac',
        genericName: 'Diclofenac Sodium',
        brandName: 'Voltaren, Cataflam',
        category: 'NSAID',
        dosageForm: 'Tablet',
        strength: '50mg',
        manufacturer: 'Various',
        activeIngredient: 'Diclofenac Sodium',
        indications: 'Pain, inflammation, arthritis, acute gout, migraine',
        contraindications: 'Active peptic ulcer, severe heart failure, pregnancy third trimester',
        sideEffects: 'Stomach pain, nausea, headache, dizziness, rash',
        dosageAdult: '50-75mg',
        dosageChild: 'Not recommended <14 years',
        frequency: 'Twice or three times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '12.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIBIOTICS
      {
        name: 'Amoxicillin',
        genericName: 'Amoxicillin',
        brandName: 'Amoxil, Trimox',
        category: 'Antibiotic',
        dosageForm: 'Capsule',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Amoxicillin Trihydrate',
        indications: 'Bacterial infections: respiratory, urinary tract, skin, ear infections',
        contraindications: 'Penicillin allergy, infectious mononucleosis',
        sideEffects: 'Diarrhea, nausea, rash, allergic reactions',
        dosageAdult: '250-500mg',
        dosageChild: '20-40mg/kg/day',
        frequency: 'Three times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '15.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Amoxicillin-Clavulanate',
        genericName: 'Amoxicillin and Clavulanic Acid',
        brandName: 'Augmentin, Co-Amoxiclav',
        category: 'Antibiotic',
        dosageForm: 'Tablet',
        strength: '625mg (500/125)',
        manufacturer: 'Various',
        activeIngredient: 'Amoxicillin + Clavulanic Acid',
        indications: 'Bacterial infections: respiratory, urinary, skin, dental',
        contraindications: 'Penicillin allergy, history of cholestatic jaundice',
        sideEffects: 'Diarrhea, nausea, vomiting, rash, hepatitis',
        dosageAdult: '625mg',
        dosageChild: '25-45mg/kg/day',
        frequency: 'Twice or three times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '25.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Azithromycin',
        genericName: 'Azithromycin',
        brandName: 'Zithromax, Z-Pack',
        category: 'Antibiotic',
        dosageForm: 'Tablet',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Azithromycin Dihydrate',
        indications: 'Respiratory infections, sexually transmitted infections, skin infections',
        contraindications: 'Hypersensitivity to macrolides, severe liver disease',
        sideEffects: 'Nausea, diarrhea, abdominal pain, headache',
        dosageAdult: '500mg day 1, then 250mg',
        dosageChild: '10mg/kg day 1, then 5mg/kg',
        frequency: 'Once daily for 3-5 days',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '35.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Ciprofloxacin',
        genericName: 'Ciprofloxacin',
        brandName: 'Cipro, Ciproxin',
        category: 'Antibiotic',
        dosageForm: 'Tablet',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Ciprofloxacin Hydrochloride',
        indications: 'Urinary tract infections, respiratory infections, skin infections',
        contraindications: 'Children under 18, pregnancy, tendon disorders',
        sideEffects: 'Nausea, diarrhea, dizziness, tendon rupture (rare)',
        dosageAdult: '250-750mg',
        dosageChild: 'Not recommended',
        frequency: 'Twice daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '20.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Metronidazole',
        genericName: 'Metronidazole',
        brandName: 'Flagyl',
        category: 'Antibiotic',
        dosageForm: 'Tablet',
        strength: '400mg',
        manufacturer: 'Various',
        activeIngredient: 'Metronidazole',
        indications: 'Anaerobic bacterial infections, protozoal infections, dental infections',
        contraindications: 'First trimester pregnancy, alcohol consumption',
        sideEffects: 'Nausea, metallic taste, headache, dark urine',
        dosageAdult: '400-500mg',
        dosageChild: '7.5mg/kg',
        frequency: 'Three times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '10.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIHYPERTENSIVES
      {
        name: 'Amlodipine',
        genericName: 'Amlodipine Besylate',
        brandName: 'Norvasc',
        category: 'Antihypertensive',
        dosageForm: 'Tablet',
        strength: '5mg',
        manufacturer: 'Various',
        activeIngredient: 'Amlodipine Besylate',
        indications: 'Hypertension, angina, coronary artery disease',
        contraindications: 'Cardiogenic shock, severe aortic stenosis',
        sideEffects: 'Ankle swelling, headache, dizziness, flushing',
        dosageAdult: '5-10mg',
        dosageChild: 'Not recommended',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '18.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Lisinopril',
        genericName: 'Lisinopril',
        brandName: 'Prinivil, Zestril',
        category: 'Antihypertensive',
        dosageForm: 'Tablet',
        strength: '10mg',
        manufacturer: 'Various',
        activeIngredient: 'Lisinopril Dihydrate',
        indications: 'Hypertension, heart failure, post-myocardial infarction',
        contraindications: 'Pregnancy, bilateral renal artery stenosis, angioedema',
        sideEffects: 'Dry cough, dizziness, headache, fatigue',
        dosageAdult: '10-40mg',
        dosageChild: '0.07mg/kg',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '15.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Losartan',
        genericName: 'Losartan Potassium',
        brandName: 'Cozaar',
        category: 'Antihypertensive',
        dosageForm: 'Tablet',
        strength: '50mg',
        manufacturer: 'Various',
        activeIngredient: 'Losartan Potassium',
        indications: 'Hypertension, diabetic nephropathy, heart failure',
        contraindications: 'Pregnancy, bilateral renal artery stenosis',
        sideEffects: 'Dizziness, fatigue, hypotension, hyperkalemia',
        dosageAdult: '25-100mg',
        dosageChild: 'Not recommended',
        frequency: 'Once or twice daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '22.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Hydrochlorothiazide',
        genericName: 'Hydrochlorothiazide',
        brandName: 'Microzide',
        category: 'Diuretic',
        dosageForm: 'Tablet',
        strength: '25mg',
        manufacturer: 'Various',
        activeIngredient: 'Hydrochlorothiazide',
        indications: 'Hypertension, edema, heart failure',
        contraindications: 'Anuria, severe renal failure, hypersensitivity to sulfonamides',
        sideEffects: 'Hypokalemia, dizziness, muscle cramps, increased urination',
        dosageAdult: '12.5-50mg',
        dosageChild: '1-2mg/kg/day',
        frequency: 'Once daily in morning',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '10.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // DIABETES MEDICATIONS
      {
        name: 'Metformin',
        genericName: 'Metformin Hydrochloride',
        brandName: 'Glucophage',
        category: 'Antidiabetic',
        dosageForm: 'Tablet',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Metformin Hydrochloride',
        indications: 'Type 2 diabetes mellitus',
        contraindications: 'Severe renal impairment, metabolic acidosis, pregnancy',
        sideEffects: 'Nausea, diarrhea, abdominal pain, metallic taste',
        dosageAdult: '500-1000mg',
        dosageChild: '10+ years: 500mg',
        frequency: 'Twice daily with meals',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '12.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },
      {
        name: 'Glimepiride',
        genericName: 'Glimepiride',
        brandName: 'Amaryl',
        category: 'Antidiabetic',
        dosageForm: 'Tablet',
        strength: '2mg',
        manufacturer: 'Various',
        activeIngredient: 'Glimepiride',
        indications: 'Type 2 diabetes mellitus',
        contraindications: 'Type 1 diabetes, diabetic ketoacidosis, severe renal/hepatic impairment',
        sideEffects: 'Hypoglycemia, weight gain, nausea, headache',
        dosageAdult: '1-4mg',
        dosageChild: 'Not recommended',
        frequency: 'Once daily before breakfast',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '18.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIHISTAMINES
      {
        name: 'Cetirizine',
        genericName: 'Cetirizine Hydrochloride',
        brandName: 'Zyrtec',
        category: 'Antihistamine',
        dosageForm: 'Tablet',
        strength: '10mg',
        manufacturer: 'Various',
        activeIngredient: 'Cetirizine Hydrochloride',
        indications: 'Allergic rhinitis, urticaria, hay fever',
        contraindications: 'Severe renal impairment, hypersensitivity',
        sideEffects: 'Drowsiness, fatigue, dry mouth, headache',
        dosageAdult: '10mg',
        dosageChild: '6+ years: 5-10mg',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '8.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Loratadine',
        genericName: 'Loratadine',
        brandName: 'Claritin',
        category: 'Antihistamine',
        dosageForm: 'Tablet',
        strength: '10mg',
        manufacturer: 'Various',
        activeIngredient: 'Loratadine',
        indications: 'Allergic rhinitis, chronic urticaria, seasonal allergies',
        contraindications: 'Hypersensitivity to loratadine',
        sideEffects: 'Headache, fatigue, dry mouth (less sedating)',
        dosageAdult: '10mg',
        dosageChild: '2+ years: 5mg',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '10.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },

      // GASTROINTESTINAL
      {
        name: 'Omeprazole',
        genericName: 'Omeprazole',
        brandName: 'Prilosec, Losec',
        category: 'Proton Pump Inhibitor',
        dosageForm: 'Capsule',
        strength: '20mg',
        manufacturer: 'Various',
        activeIngredient: 'Omeprazole',
        indications: 'GERD, peptic ulcer, gastritis, H. pylori eradication',
        contraindications: 'Hypersensitivity to PPIs',
        sideEffects: 'Headache, diarrhea, nausea, abdominal pain',
        dosageAdult: '20-40mg',
        dosageChild: '1+ years: 10-20mg',
        frequency: 'Once daily before breakfast',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '15.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Ranitidine',
        genericName: 'Ranitidine Hydrochloride',
        brandName: 'Zantac',
        category: 'H2 Receptor Antagonist',
        dosageForm: 'Tablet',
        strength: '150mg',
        manufacturer: 'Various',
        activeIngredient: 'Ranitidine Hydrochloride',
        indications: 'Peptic ulcer, GERD, gastritis, acid reflux',
        contraindications: 'Hypersensitivity to ranitidine',
        sideEffects: 'Headache, dizziness, constipation, diarrhea',
        dosageAdult: '150-300mg',
        dosageChild: '2-4mg/kg',
        frequency: 'Twice daily or once at bedtime',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '12.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Ondansetron',
        genericName: 'Ondansetron',
        brandName: 'Zofran',
        category: 'Antiemetic',
        dosageForm: 'Tablet',
        strength: '4mg',
        manufacturer: 'Various',
        activeIngredient: 'Ondansetron Hydrochloride',
        indications: 'Nausea and vomiting (chemotherapy, post-operative, gastroenteritis)',
        contraindications: 'Congenital long QT syndrome, hypersensitivity',
        sideEffects: 'Headache, constipation, dizziness, fatigue',
        dosageAdult: '4-8mg',
        dosageChild: '4+ years: 4mg',
        frequency: 'Every 8 hours as needed',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '25.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // RESPIRATORY
      {
        name: 'Salbutamol',
        genericName: 'Salbutamol Sulfate',
        brandName: 'Ventolin, Albuterol',
        category: 'Bronchodilator',
        dosageForm: 'Inhaler',
        strength: '100mcg/puff',
        manufacturer: 'Various',
        activeIngredient: 'Salbutamol Sulfate',
        indications: 'Asthma, COPD, bronchospasm, wheezing',
        contraindications: 'Hypersensitivity to salbutamol',
        sideEffects: 'Tremor, tachycardia, headache, palpitations',
        dosageAdult: '2 puffs (200mcg)',
        dosageChild: '1-2 puffs',
        frequency: 'Every 4-6 hours as needed',
        routeOfAdministration: 'Inhalation',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '35.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Montelukast',
        genericName: 'Montelukast Sodium',
        brandName: 'Singulair',
        category: 'Leukotriene Modifier',
        dosageForm: 'Tablet',
        strength: '10mg',
        manufacturer: 'Various',
        activeIngredient: 'Montelukast Sodium',
        indications: 'Asthma prophylaxis, allergic rhinitis',
        contraindications: 'Hypersensitivity to montelukast',
        sideEffects: 'Headache, abdominal pain, mood changes',
        dosageAdult: '10mg',
        dosageChild: '6-14 years: 5mg',
        frequency: 'Once daily at bedtime',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '30.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIMALARIALS
      {
        name: 'Artemether-Lumefantrine',
        genericName: 'Artemether and Lumefantrine',
        brandName: 'Coartem',
        category: 'Antimalarial',
        dosageForm: 'Tablet',
        strength: '20/120mg',
        manufacturer: 'Novartis',
        activeIngredient: 'Artemether + Lumefantrine',
        indications: 'Uncomplicated malaria (Plasmodium falciparum)',
        contraindications: 'Severe malaria, first trimester pregnancy, cardiac arrhythmias',
        sideEffects: 'Headache, dizziness, nausea, fatigue, palpitations',
        dosageAdult: '4 tablets',
        dosageChild: 'Weight-based dosing',
        frequency: 'Twice daily for 3 days',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '45.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // VITAMINS & SUPPLEMENTS
      {
        name: 'Vitamin C',
        genericName: 'Ascorbic Acid',
        brandName: 'Various',
        category: 'Vitamin',
        dosageForm: 'Tablet',
        strength: '500mg',
        manufacturer: 'Various',
        activeIngredient: 'Ascorbic Acid',
        indications: 'Vitamin C deficiency, immune support, antioxidant',
        contraindications: 'Kidney stones, hemochromatosis',
        sideEffects: 'Stomach upset, diarrhea (high doses)',
        dosageAdult: '500-1000mg',
        dosageChild: '100-250mg',
        frequency: 'Once or twice daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store in cool, dry place',
        shelfLife: '3 years',
        costPerUnit: '5.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Folic Acid',
        genericName: 'Folic Acid',
        brandName: 'Various',
        category: 'Vitamin',
        dosageForm: 'Tablet',
        strength: '5mg',
        manufacturer: 'Various',
        activeIngredient: 'Folic Acid',
        indications: 'Folate deficiency, pregnancy, anemia prevention',
        contraindications: 'Pernicious anemia (untreated B12 deficiency)',
        sideEffects: 'Rare: allergic reactions, sleep disturbances',
        dosageAdult: '400mcg-5mg',
        dosageChild: '100-400mcg',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '6.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },
      {
        name: 'Multivitamin',
        genericName: 'Multivitamin',
        brandName: 'Centrum, One-A-Day',
        category: 'Vitamin',
        dosageForm: 'Tablet',
        strength: 'Various',
        manufacturer: 'Various',
        activeIngredient: 'Multiple vitamins and minerals',
        indications: 'Nutritional supplement, vitamin deficiency prevention',
        contraindications: 'Hypervitaminosis, specific vitamin allergies',
        sideEffects: 'Stomach upset, constipation (iron content)',
        dosageAdult: '1 tablet',
        dosageChild: 'Age-appropriate formulation',
        frequency: 'Once daily with food',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store in cool, dry place',
        shelfLife: '2 years',
        costPerUnit: '10.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },

      // ANTIFUNGALS
      {
        name: 'Fluconazole',
        genericName: 'Fluconazole',
        brandName: 'Diflucan',
        category: 'Antifungal',
        dosageForm: 'Capsule',
        strength: '150mg',
        manufacturer: 'Various',
        activeIngredient: 'Fluconazole',
        indications: 'Vaginal candidiasis, oral thrush, fungal infections',
        contraindications: 'Hypersensitivity to azoles, concurrent terfenadine',
        sideEffects: 'Nausea, headache, abdominal pain, rash',
        dosageAdult: '150mg single dose or 50-400mg',
        dosageChild: '3-12mg/kg',
        frequency: 'Once (single dose) or once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '30.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIVIRALS
      {
        name: 'Acyclovir',
        genericName: 'Acyclovir',
        brandName: 'Zovirax',
        category: 'Antiviral',
        dosageForm: 'Tablet',
        strength: '400mg',
        manufacturer: 'Various',
        activeIngredient: 'Acyclovir',
        indications: 'Herpes simplex, genital herpes, shingles, chickenpox',
        contraindications: 'Hypersensitivity to acyclovir',
        sideEffects: 'Nausea, diarrhea, headache, fatigue',
        dosageAdult: '200-800mg',
        dosageChild: '20mg/kg',
        frequency: '5 times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '25.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // STEROIDS
      {
        name: 'Prednisolone',
        genericName: 'Prednisolone',
        brandName: 'Prelone, Orapred',
        category: 'Corticosteroid',
        dosageForm: 'Tablet',
        strength: '5mg',
        manufacturer: 'Various',
        activeIngredient: 'Prednisolone',
        indications: 'Inflammation, asthma exacerbation, allergic reactions, autoimmune diseases',
        contraindications: 'Systemic fungal infections, live vaccines',
        sideEffects: 'Weight gain, mood changes, increased appetite, insomnia',
        dosageAdult: '5-60mg',
        dosageChild: '1-2mg/kg',
        frequency: 'Once daily in morning',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '15.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTICOAGULANTS
      {
        name: 'Aspirin',
        genericName: 'Acetylsalicylic Acid',
        brandName: 'Ecosprin, Disprin',
        category: 'Antiplatelet',
        dosageForm: 'Tablet',
        strength: '75mg',
        manufacturer: 'Various',
        activeIngredient: 'Acetylsalicylic Acid',
        indications: 'Cardiovascular disease prevention, pain, fever, inflammation',
        contraindications: 'Active peptic ulcer, hemophilia, children <16 (Reye syndrome)',
        sideEffects: 'Stomach upset, bleeding risk, tinnitus (high doses)',
        dosageAdult: '75-325mg (cardioprotective)',
        dosageChild: 'Not recommended <16 years',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '5.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },

      // ANTACIDS
      {
        name: 'Aluminum Hydroxide',
        genericName: 'Aluminum Hydroxide',
        brandName: 'Maalox, Aludrox',
        category: 'Antacid',
        dosageForm: 'Suspension',
        strength: '400mg/5ml',
        manufacturer: 'Various',
        activeIngredient: 'Aluminum Hydroxide',
        indications: 'Heartburn, acid indigestion, peptic ulcer',
        contraindications: 'Severe renal impairment, hypophosphatemia',
        sideEffects: 'Constipation, aluminum toxicity (long-term use)',
        dosageAdult: '5-10ml',
        dosageChild: '2.5-5ml',
        frequency: 'After meals and at bedtime',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '2 years',
        costPerUnit: '8.00',
        isControlled: false,
        prescriptionRequired: false,
        isActive: true
      },

      // MUSCLE RELAXANTS
      {
        name: 'Methocarbamol',
        genericName: 'Methocarbamol',
        brandName: 'Robaxin',
        category: 'Muscle Relaxant',
        dosageForm: 'Tablet',
        strength: '750mg',
        manufacturer: 'Various',
        activeIngredient: 'Methocarbamol',
        indications: 'Muscle spasms, musculoskeletal pain, back pain',
        contraindications: 'Myasthenia gravis, hypersensitivity',
        sideEffects: 'Drowsiness, dizziness, nausea, headache',
        dosageAdult: '750-1500mg',
        dosageChild: 'Not recommended',
        frequency: '3-4 times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '20.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTIDEPRESSANTS
      {
        name: 'Sertraline',
        genericName: 'Sertraline Hydrochloride',
        brandName: 'Zoloft',
        category: 'Antidepressant',
        dosageForm: 'Tablet',
        strength: '50mg',
        manufacturer: 'Various',
        activeIngredient: 'Sertraline Hydrochloride',
        indications: 'Depression, anxiety, OCD, PTSD, panic disorder',
        contraindications: 'MAO inhibitor use, pimozide use',
        sideEffects: 'Nausea, diarrhea, insomnia, sexual dysfunction',
        dosageAdult: '25-200mg',
        dosageChild: '13+ years: 25-50mg',
        frequency: 'Once daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '35.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // ANTICONVULSANTS
      {
        name: 'Carbamazepine',
        genericName: 'Carbamazepine',
        brandName: 'Tegretol',
        category: 'Anticonvulsant',
        dosageForm: 'Tablet',
        strength: '200mg',
        manufacturer: 'Various',
        activeIngredient: 'Carbamazepine',
        indications: 'Epilepsy, trigeminal neuralgia, bipolar disorder',
        contraindications: 'Bone marrow depression, MAO inhibitor use, porphyria',
        sideEffects: 'Dizziness, drowsiness, nausea, ataxia, rash',
        dosageAdult: '200-1600mg/day',
        dosageChild: '10-20mg/kg/day',
        frequency: 'Twice or three times daily',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '25.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      },

      // PROKINETICS
      {
        name: 'Metoclopramide',
        genericName: 'Metoclopramide Hydrochloride',
        brandName: 'Reglan',
        category: 'Prokinetic',
        dosageForm: 'Tablet',
        strength: '10mg',
        manufacturer: 'Various',
        activeIngredient: 'Metoclopramide Hydrochloride',
        indications: 'Nausea, vomiting, gastroparesis, migraine',
        contraindications: 'GI obstruction, pheochromocytoma, seizure disorder',
        sideEffects: 'Drowsiness, restlessness, dystonia, tardive dyskinesia',
        dosageAdult: '10mg',
        dosageChild: '0.1-0.2mg/kg',
        frequency: 'Three times daily before meals',
        routeOfAdministration: 'Oral',
        storageConditions: 'Store at room temperature',
        shelfLife: '3 years',
        costPerUnit: '12.00',
        isControlled: false,
        prescriptionRequired: true,
        isActive: true
      }
    ];

    // Insert medications
    const inserted = await db.insert(medications).values(commonMedications).returning();

    console.log(`✨ Successfully seeded ${inserted.length} medications`);
    return { 
      message: 'Medications seeded successfully', 
      count: inserted.length,
      medications: inserted.map(m => m.name)
    };
  } catch (error) {
    console.error('❌ Error seeding medications:', error);
    throw error;
  }
}

